### ISSUE TITLE
many index pages and none matches the github page!

### ISSUE THREAD

**Issue by eslamabdo164** [zero-to-mastery/book-tracker#55]
hi all , 
I have just started my first contribution and i want to contribute to this book tracker project , 
but I can't find the index.html file that shared on the github page  in the project file
I mean this link : https://zero-to-mastery.github.io/book-tracker/ 
instead I have other index pages , 
could anyone help clarify this to me . 

Thanks in advance

**Comment by N8Brown1** [comment]
Hi!
I just started looking through this project myself. From what I can see, it appears that the index.html file currently tied to the Github pages is at the following path:

book-tracker/public/index.html

Somebody please correct me if I am wrong, otherwise, I hope that helps!

- Nate

**Comment by itshally** [comment]
Hi :) , 

since this react application is being deployed to Github pages, you can find that **index.html** file that you are looking for in the _**gh-pages** branch_. You don't need to modify it though. However, all in all, the **components** of the entire application (which is inside the **src** folder ) is being ran to the:
 **book-tracker/public/index.html** of the `<div>` tag. 

See Line 22: `<div id="root"></div>`
