### ISSUE TITLE
Page structure & functionality

### ISSUE THREAD

**Issue by diogomatoschaves** [zero-to-mastery/book-tracker#83]
Hey, 

I'd like to contribute more to this project, but I'd like to know if there is a particular direction the owners would like the project to go? At the moment it's not very clear what kind of functionality the page should have, i.e., what should appear on the wish list, reading list, homepage, where do the books added go, etc.

Thanks!

**Comment by davidoliver278** [comment]
Hi Diogo. Unfortunetely I have the same question...

**Comment by inkerina** [comment]
Same question!

**Comment by matteo1976** [comment]
same for me

**Comment by dylan-ztm** [comment]
I have the same question.

**Comment by nnhhiilliisstt** [comment]
same here , need more clarification regarding the issue

**Comment by phat-marc** [comment]
@nnhhiilliisstt, @dylan-ztm, Since this project is a group effort, the direction it takes is up to us/any and all contributors. So I suggest we start by building a guide that makes it easy for newcomers to understand what the project's aims are, and to direct their efforts. 
I think that we should start by updating the readme.md to offer a comprehensive guide. The steps to do this can be:

1.  Read through readme.md carefully
2.  Add relevant headings, including
      - Contributing Guideline
      - App Structure
      - App Functionality

Then the next step would be to populate the sections under each heading, but we should open separate issues for each section.
There is a second file called CONTIRBUTING.md which contains some info that belongs in read.me and some stuff that should be opened as issues. I am going to open a separate issue dedicated to solving this.

If everyone agrees with my above suggestion then this issue can be considered as complete when the readme.md file has a layout that serve as a starting point for answering the original questions.

**Comment by sophiabrandt** [comment]
I think that's a good approach! Like @phat-marc said: this is a community effort, so you are free to move the project in the direction you want.
I'll add the label "up for grabs" to encourage participation.

**Comment by RichardJonBacon** [comment]
Hi, I'm interested in contributing to this in order to encourage participation.
As a starting point I'll have a go at updating the README. I'll use some templates I've used in the past and also try and make it consistent with other Zero To Mastery repos.

**Comment by RichardJonBacon** [comment]
I've submitted PR https://github.com/zero-to-mastery/book-tracker/pull/251 as a starting point for this.
At the moment this just adds more information to the README, the next step would be to update the CONTRIBUTING.md.

I wonder if some confusion of how to contribute stems from having both a React and JavaScript version of the app in the same repo? I understand some people may want to practice React and some vanilla JS but it does mean that the functionality of each app could go in a different direction.
